# 인덱싱과 슬라이싱을 이용한 배열의 원소 조회

## 배열 인덱싱(Indexing)
- ### index
    - 배열내의 원소의 식별번호
    - 0부터 시작 
- ### indexing 
    – index를 이용해 원소 조회
    - [] 표기법 사용
- ### 구문 
    - ndarray[index]
    - 양수는 지정한 index의 값을 조회한다. 
    - 음수는 뒤부터 조회한다. 
        - 마지막 index가 -1
    - 2차원배열의 경우 
        - arr[행index, 열index]
        - 파이썬 리스트와 차이점 (list[행][열])
    - N차원 배열의 경우
        - arr[0축 index, 1축 index, ..., n축 index]
- ### 팬시(fancy) 인덱싱
    - **여러개의 원소를 한번에 조회**할 경우 리스트에 담아 전달한다.
    - 다차원 배열의 경우 각 축별로 list로 지정
    - `arr[[1,2,3,4,5]]`
        - 1차원 배열(vector): 1,2,3,4,5 번 index의 원소들 한번에 조회
    - `arr[[0,3],[ 1,4]]`
        - [0,3] - 1번축 index list, [1,4] - 2번축 index list
        - 2차원 배열(matrix): [0,1], [3,4] 의 원소들 조회

#### 1차원 배열

In [1]:
import numpy as np

a1 = np.arange(10)
print(a1)
print("한개:", a1[0], a1[5])
print('여러개(3, 6, 7)-fancy indexing:', a1[[3,6,7]])
print('음수index:', a1[-1])

[0 1 2 3 4 5 6 7 8 9]
한개: 0 5
여러개(3, 6, 7)-fancy indexing: [3 6 7]
음수index: 9


#### 값 변경

In [2]:
a1[0] = 100
a1

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [3]:
a1[[0,1,2]]  = 10000   # 여러 index의 값을 한번에 같은 값으로 변경
a1

array([10000, 10000, 10000,     3,     4,     5,     6,     7,     8,
           9])

In [4]:
a1[[3,5,7]] = [700,800,900] # 여러 index의 값을 서로 다른 값으로 변경
a1

array([10000, 10000, 10000,   700,     4,   800,     6,   900,     8,
           9])

#### 다차원 배열

In [8]:
a2 = np.arange(30).reshape(5, 6)
print(a2)
print('0축:',a2[0])  #0축
print('(0축,1축)',a2[0, 3])
print('[0축들],[1축들]:',a2[ [2,3,4] , [1,1,2] ])  #[0축들, 1축들])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
0축: [0 1 2 3 4 5]
(0축,1축) 3
[0축들],[1축들]: [13 19 26]


## 슬라이싱
- 배열의 부분 집합을 하위배열로 조회 및 변경하는 방식
- ndarry[start : stop : step ]
    - start : 시작 인덱스. 기본값 0
    - stop : 끝 index. stop은 포함하지 않는다. 기본값 마지막 index
    - step : 증감 간격. 기본값 1)

In [9]:
a1 = np.arange(100)
print(a1.shape)
a1[5:20]  # 5 ~ 20-1, step: 1

(100,)


array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [10]:
a1[5:75:5]  # 5 ~ 75-1: step: 5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70])

### 다차원 배열 슬라이싱
- 각 축에 slicing 문법 적용
- 2차원의 경우
    - arr [행 slicing, 열 slicing]
        - `arr[:3, :]`
    - `,` 로 행과 열을 구분한 다중 슬라이싱 사용
- 다차원의 경우
    - arr[0축 slicing, 1축 slicing, ..., n축 slicing]
- slicing과 indexing 문법은 같이 쓸 수 있다.
- 모든 축에 index를 지정할 필요는 없다.

In [16]:
# a2[0축 , 1축]
print(a2)
print('--------------------')
print(a2[:3])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
--------------------
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [17]:
a2[1:4, 1:5]

array([[ 7,  8,  9, 10],
       [13, 14, 15, 16],
       [19, 20, 21, 22]])

In [18]:
a2[1:4, [2,4,5]] #0축: slicing, 1축: fancy indexing

array([[ 8, 10, 11],
       [14, 16, 17],
       [20, 22, 23]])

### 슬라이싱은 원본에 대한 View 
- slicing한 결과는 새로운 배열을 생성하는 것이 아니라 기존 배열을 참조한다.
- slicing한 배열의 원소를 변경하면 원본 배열의 것도 바뀐다.
- 배열.copy()
    - 배열을 복사한 새로운 배열 생성
    - 복사후 처리하면 원본이 바뀌지 않는다.

#### slicing 후 원소를 변경하면 원본의 원소도 변경됨

In [19]:
b = a1[:10]
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# b는 a1을 slicing 한 결과. b의 원소를 변경하면 a1의 원소도 같이 변경 -> (slicing: shallow copy)
b[0] = 1000
b

array([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9])

#### 원본을 복사 후 값변경 -> 원본 변경 x

In [21]:
b2 = a1[:10].copy()  # copy() 깊은복사(deep copy)
b2[0] = 50000
b2

array([50000,     1,     2,     3,     4,     5,     6,     7,     8,
           9])

In [22]:
b

array([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9])

## boolean indexing
- Index 연산자에 Boolean 배열을 넣으면 True인 index의 값만 조회 (False가 있는 index는 조회하지 않는다.)
- ndarray내의 원소 중에서 원하는 조건의 값들만 조회할 때 사용

In [23]:
import numpy as np
# a,b 동일한 shape
a = np.arange(1,10)
b = np.random.choice([True, False], 9)
print(a)
print(b)

[1 2 3 4 5 6 7 8 9]
[False  True  True False  True False  True  True False]


In [24]:
a[b] # b의 True가 있는 index의 값을 a에서 조회

array([2, 3, 5, 7, 8])

#### and: & , or: |, not: ~
#### 파이썬 and, or, not 키워드 연산자는 사용안됨.(넘파이, 판다스)
#### 피연산자는 ( )로 묶어준다.(넘파이, 판다스)

In [25]:
a[~((a>5) & (a<9))]

array([1, 2, 3, 4, 5, 9])

### np.where()
- np.where(boolean 배열) - True인 index를 반환
- boolean연산과 같이쓰면 특정 조건을 만족하는 원소의 index조회됨.
- np.where(boolean 배열, True를 대체할 값, False를 대체할 값)
    - True와 False를 다른 값으로 변경한다.

In [26]:
np.where([True, False, True])  #True의 index들을 ndarray로 묶어서 반환. 반환타입: Tuple (축별로 묶어서 반환)

(array([0, 2], dtype=int64),)

In [27]:
np.where([[True, False], [True, False]])
# [0, 1]: 0축의 index들, [0, 0]: 1축의 index들  ===> (실제 값의 index는 같은 index끼리 묶어준다.) (0, 0), (1, 0)

(array([0, 1], dtype=int64), array([0, 0], dtype=int64))

- 2차원도 마찮가지
    - 단 where는 축별로 배열이 반환된다. [0,1], [2,3] => (0,2)  (1,3)
    - 보통 Vector에 적용한다.

In [29]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
# True, False 를 다른 값으로 변경
np.where(a > 5, "5이상", "5미만")

array(['5미만', '5미만', '5미만', '5미만', '5미만', '5이상', '5이상', '5이상', '5이상'],
      dtype='<U3')

In [30]:
# value자리에 배열객체를 넣으면 비교한 조건의 값이 그대로 나온다.
np.where(a>5, "5이상", a)  

array(['1', '2', '3', '4', '5', '5이상', '5이상', '5이상', '5이상'], dtype='<U11')

### 기타
- np.any(boolean 배열)
    - 배열에 True가 하나라도 있으면 True 반환
- np.all(boolean 배열)
    - 배열의 모든 원소가 True이면 True 반환

In [33]:
# 특정조건을 만족하는 값이 하나라도 있는지 확인 -> any()
# 특정조건을 배열의 모든 원소가 만족하는지 확인 -> all()
print(np.any(a > 5))
print(np.all(a > 5))

True
False


### 정렬
- np.sort(arr): arr을 정렬
- np.argsort(arr): 정렬 후 index를 반환

In [35]:
x = np.random.randint(10,20,10)
x

array([10, 12, 12, 18, 18, 18, 18, 10, 18, 10])

In [36]:
y = np.sort(x) 
#x를 정렬한 새로운 배열을 반환 (원본을 정렬하지 않는다.)
#오름차순 정렬
print(x)
print(y)

[10 12 12 18 18 18 18 10 18 10]
[10 10 10 12 12 18 18 18 18 18]


In [37]:
# 내림차순정렬 - sort()로 정렬한 뒤에서 reverse시킨다.
y2 = np.sort(x)[::-1]
y2

array([18, 18, 18, 18, 18, 12, 12, 10, 10, 10])

In [39]:
# 배열객체.sort() => 원본이 정렬
x.sort()
x

array([10, 10, 10, 12, 12, 18, 18, 18, 18, 18])

In [40]:
x2 = np.random.randint(10,20,size=(5,4))
print(x2)
y = np.sort(x2, axis=0)
print(y)

[[11 18 12 14]
 [16 10 12 16]
 [10 11 10 16]
 [10 12 19 17]
 [16 15 16 10]]
[[10 10 10 10]
 [10 11 12 14]
 [11 12 12 16]
 [16 15 16 16]
 [16 18 19 17]]


In [41]:
np.sort(x2, axis=1)  #axis=None(기본) None-마지막축을 기준으로 정렬

array([[11, 12, 14, 18],
       [10, 12, 16, 16],
       [10, 10, 11, 16],
       [10, 12, 17, 19],
       [10, 15, 16, 16]])

In [42]:
x3 = np.random.randint(10,20,10)
print(x3)
y = np.argsort(x3)
#  정렬한 것을 index로 반환.
print(y)

[12 17 13 17 19 10 12 12 14 15]
[5 0 6 7 2 8 9 1 3 4]
